@startuml
!include style.puml
actor User as user USER_COLOR
participant "CommandBox" as CB UI_COLOR
participant "CommandHistory" as CH

User -> CB : Press UP
activate CB
CB -> CH : getPrevCommand()
CH --> CB : previous-command-string (or NO_PREV_OR_NEXT_COMMAND)
CB -> CB : setText(previous-command)
deactivate CB

User -> CB : Press DOWN
activate CB
CB -> CH : getNextCommand()
CH --> CB : next-command-string (or NO_PREV_OR_NEXT_COMMAND)
CB -> CB : setText(next-command or buffer)
deactivate CB
@enduml
